from __future__ import annotations

import os

import yaml


def load_postings(path: str) -> list[dict]:
    if not os.path.exists(path):
        return []
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    return data or []


def save_postings(path: str, postings: list[dict]) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# Fetched job postings. Generated by fetch-postings.py — do not hand-edit\n"
            "# except to delete entries you're no longer interested in.\n"
        )
        yaml.safe_dump(postings, f, sort_keys=False)


def merge_new_postings(
    existing: list[dict], fetched: list[dict], today: str
) -> tuple[list[dict], list[dict]]:
    existing_ids = {p["id"] for p in existing}
    merged = list(existing)
    new_postings = []
    for posting in fetched:
        if posting["id"] in existing_ids:
            continue
        posting = dict(posting)
        posting["first_seen"] = today
        posting["notified"] = False
        merged.append(posting)
        new_postings.append(posting)
        existing_ids.add(posting["id"])
    return merged, new_postings


def mark_notified(postings: list[dict], ids: set[str]) -> None:
    for posting in postings:
        if posting["id"] in ids:
            posting["notified"] = True
